name: build_site

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build the website
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - name: "Build the site"
        run: make html

      - name: "Deploy to Netlify"
        if: github.ref == 'refs/heads/main'
        run: make deploy-prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
